---
# Yum
- name: Yum
  block:
    - name: Add epel
      yum:
        name: epel-release
        update_cache: yes

    - name: Install Software
      yum: 
        name: "{{ wildfly_packages }}"
        state: present
        update_cache: yes

# Set ip from facts
- name: Set ip from facts
  set_fact:
    ip: "{{ ansible_eth0.ipv4.address }}"

# Pip install pexpect
- name: Pip install pexpect
  pip:
    name: pexpect

# Install Wildfly
- name: Install Wildfly
  block: 
  - name: Download wildfly
    unarchive:
      src: "https://download.jboss.org/wildfly/{{ wildfly_wildfly_version }}.Final/wildfly-{{ wildfly_wildfly_version }}.Final.tar.gz"
      dest: "/opt"
      remote_src: yes

  - name: Link wildfly
    file:
      src: "/opt/wildfly-{{ wildfly_wildfly_version }}.Final"
      dest: /opt/wildfly
      owner: root
      group: root
      state: link      

  - name: Change localhost address by Ip
    replace:
      path: "{{ wildfly_wildfly_install }}/standalone/configuration/standalone.xml"
      regexp: ':127.0.0.1'
      replace: ":{{ ip }}"
    
  - name: Add user admin
    expect:
      command: "{{ wildfly_wildfly_install }}/bin/add-user.sh"
      responses:
        '(?i)a\)\:': "a"
        '(?i)Username \:': "admin"
        '(?i)Password \:': "password"
        '(?i)\]\:': ""
        '(?i)no\?': "yes"  
      echo: yes
      timeout: 3

  # Templates
  - name: Service Wildfly Template
    template: 
      src: wildfly_service.j2
      dest: /etc/systemd/system/wildfly.service
  
  # Wildfly service.
  - name: Wildfly service
    service: 
      name: wildfly
      state: restarted
      enabled: yes